//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAssignment.ReportReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportReference.Report1Soap")]
    public interface Report1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLatestCustomers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLatestCustomers(string destinationLocation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLatestCustomers", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetLatestCustomersAsync(string destinationLocation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLatestDriver", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetLatestDriver(string driverID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLatestDriver", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetLatestDriverAsync(string driverID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Report1SoapChannel : WebAssignment.ReportReference.Report1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Report1SoapClient : System.ServiceModel.ClientBase<WebAssignment.ReportReference.Report1Soap>, WebAssignment.ReportReference.Report1Soap {
        
        public Report1SoapClient() {
        }
        
        public Report1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Report1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Report1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Report1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetLatestCustomers(string destinationLocation) {
            return base.Channel.GetLatestCustomers(destinationLocation);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetLatestCustomersAsync(string destinationLocation) {
            return base.Channel.GetLatestCustomersAsync(destinationLocation);
        }
        
        public System.Data.DataSet GetLatestDriver(string driverID) {
            return base.Channel.GetLatestDriver(driverID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetLatestDriverAsync(string driverID) {
            return base.Channel.GetLatestDriverAsync(driverID);
        }
    }
}
