<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="About.aspx.cs" Inherits="CRUD.About" MasterPageFile="~/Site2.Master" %>

<script runat="server">

</script>

<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder2" runat="server" >
    <style type="text/css">
        .auto-style1 {
            width: 230px;
        }
    </style>

    <div>
    
        <strong style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 238, 218);">Comfort4u</strong><span style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(246, 238, 218);">, a Malaysian icon and the leader of the express bus industry, is one of the most prominent and popular household brand names in Southeast Asia region, serving more than 
        200 destinations, covering all major cities and towns with 1,000 daily departures across Peninsular Malaysia and Singapore. Using the latest advancement in bus technologies, design and comfort, Transnasional provides safe, enjoyable and affordable travel.<span class="Apple-converted-space">&nbsp;</span></span><br style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 238, 218);" />
        <br style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 238, 218);" />
        <span style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(246, 238, 218);">Having been in the express bus industry for over 3 decades, <strong style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 238, 218);">Comfort4u</strong> has led the industry by constantly innovating itself. The pioneer in the electronic ticketing system,
        <strong style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 238, 218);">Comfort4u</strong> has made the booking process much faster, accurate and efficient as it enables the passengers to plan their journey, make reservation and purchase express bus tickets at any ticketing counter, 60 days in advance including return and multiple journeys trips. On top of that, 170 ticketing agents including selected Petronas Mesra Stores has been appointed for greater accessibility to the customers.<span class="Apple-converted-space">&nbsp;</span></span><br style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 238, 218);" />
        <br style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 238, 218);" />
        <span style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(246, 238, 218);"><strong style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 238, 218);">Comfort4u </strong>was also the first to provide insurance coverage for passenger and baggage, whereby in the case of unfortunate event, the passengers are covered for medical expenses or 
        loss of baggage.<span class="Apple-converted-space">&nbsp;</span></span><br style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 238, 218);" />
        <br style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 238, 218);" />
        <span style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(246, 238, 218);"><strong style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 238, 218);">Comfort4u</strong> Skyview, the first 69-seater jumbo coach in the country is another achievement for the brand as it provides an exciting new experience and level of comfort for the 
        super economy class coaches with features that includes aerodynamic design and ergonomic super slim contoured seats.<span class="Apple-converted-space">&nbsp;</span></span><br style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 238, 218);" />
        <br style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 238, 218);" />
        <span style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(246, 238, 218);">In addition to its regularly scheduled passenger service, <strong style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 238, 218);">Comfort4u </strong>also provides</span><em style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 238, 218);"><span class="Apple-converted-space">&nbsp;</span>courier/delivery 
        services, charter packages<span class="Apple-converted-space">&nbsp;</span></em><span style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(246, 238, 218);">and</span><em style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 238, 218);">bus advertising solutions</em><span style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(246, 238, 218);">.<span class="Apple-converted-space">&nbsp;</span></span><br style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 238, 218);" />
        <br style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 238, 218);" />
        <span style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; display: inline !important; float: none; background-color: rgb(246, 238, 218);">With so much to offer under one brand name,<span class="Apple-converted-space">&nbsp;</span></span><strong style="color: rgb(51, 51, 51); font-family: Arial; font-size: 11px; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: 17.066667556762695px; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(246, 238, 218);">Comfort4u is certainly your preferred choice!</strong></div>
    </form>
    <table align="center" cellpadding="0" cellspacing="0" class="BlackText" style="margin: 0px auto; font-size: 12px; color: rgb(0, 0, 0); font-family: Arial; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);">
        <tr class="style99">
            <td bgcolor="#f1f1f1" class="auto-style1" height="59" valign="Top">
                <p>
                    <strong>ONLINE TICKETING SERVICE</strong></p>
            </td>
            <td bgcolor="#f1f1f1" valign="top" width="259">
                <p>
                    <strong><u>Hotline Operating Hours</u></strong></p>
                <p>
                    <strong>Monday to Friday</strong><br />
                    - 7.00am until 9.00pm<br />
                    <strong>Saturday to Sunday</strong><br />
                    - 9.00am until 5.00pm</p>
                <p>
                    <strong>Hotline :<span class="Apple-converted-space">&nbsp;</span></strong><br />
                    1300-88-842538<br />
                    03-2035 5525<br />
                    Email : helpdesk@eticketing.my<br />
                    (For issues on online purchase only)</p>
                <p>
                    <strong>Public Holiday &amp; Others :</strong><br />
                    012-376 3844 / 012-376 3578</p>
            </td>
        </tr>
    </table>
</asp:Content>