//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace Assignment1.ServiceReference2 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Payment", Namespace="http://schemas.datacontract.org/2004/07/Assignment1.Web")]
    public partial class Payment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string PaymentAmountField;
        
        private string ReservationBusNumberField;
        
        private string ReservationDateField;
        
        private string ReservationFromField;
        
        private string ReservationICField;
        
        private string ReservationIDField;
        
        private string ReservationNameField;
        
        private string ReservationPhoneNoField;
        
        private string ReservationSeatNumberField;
        
        private string ReservationTimeField;
        
        private string ReservationToField;
        
        private System.Nullable<decimal> ReservationTotalFareField;
        
        private System.Nullable<int> ReservationTotalSeatField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentAmount {
            get {
                return this.PaymentAmountField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentAmountField, value) != true)) {
                    this.PaymentAmountField = value;
                    this.RaisePropertyChanged("PaymentAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationBusNumber {
            get {
                return this.ReservationBusNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationBusNumberField, value) != true)) {
                    this.ReservationBusNumberField = value;
                    this.RaisePropertyChanged("ReservationBusNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationDate {
            get {
                return this.ReservationDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationDateField, value) != true)) {
                    this.ReservationDateField = value;
                    this.RaisePropertyChanged("ReservationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationFrom {
            get {
                return this.ReservationFromField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationFromField, value) != true)) {
                    this.ReservationFromField = value;
                    this.RaisePropertyChanged("ReservationFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationIC {
            get {
                return this.ReservationICField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationICField, value) != true)) {
                    this.ReservationICField = value;
                    this.RaisePropertyChanged("ReservationIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationID {
            get {
                return this.ReservationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationIDField, value) != true)) {
                    this.ReservationIDField = value;
                    this.RaisePropertyChanged("ReservationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationName {
            get {
                return this.ReservationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationNameField, value) != true)) {
                    this.ReservationNameField = value;
                    this.RaisePropertyChanged("ReservationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationPhoneNo {
            get {
                return this.ReservationPhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationPhoneNoField, value) != true)) {
                    this.ReservationPhoneNoField = value;
                    this.RaisePropertyChanged("ReservationPhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationSeatNumber {
            get {
                return this.ReservationSeatNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationSeatNumberField, value) != true)) {
                    this.ReservationSeatNumberField = value;
                    this.RaisePropertyChanged("ReservationSeatNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationTime {
            get {
                return this.ReservationTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationTimeField, value) != true)) {
                    this.ReservationTimeField = value;
                    this.RaisePropertyChanged("ReservationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationTo {
            get {
                return this.ReservationToField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationToField, value) != true)) {
                    this.ReservationToField = value;
                    this.RaisePropertyChanged("ReservationTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ReservationTotalFare {
            get {
                return this.ReservationTotalFareField;
            }
            set {
                if ((this.ReservationTotalFareField.Equals(value) != true)) {
                    this.ReservationTotalFareField = value;
                    this.RaisePropertyChanged("ReservationTotalFare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReservationTotalSeat {
            get {
                return this.ReservationTotalSeatField;
            }
            set {
                if ((this.ReservationTotalSeatField.Equals(value) != true)) {
                    this.ReservationTotalSeatField = value;
                    this.RaisePropertyChanged("ReservationTotalSeat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Reservation", Namespace="http://schemas.datacontract.org/2004/07/Assignment1.Web")]
    public partial class Reservation : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ReservationBusNumberField;
        
        private string ReservationDateField;
        
        private string ReservationFromField;
        
        private string ReservationICField;
        
        private string ReservationIDField;
        
        private string ReservationNameField;
        
        private string ReservationPhoneNoField;
        
        private string ReservationSeatNumberField;
        
        private string ReservationTimeField;
        
        private string ReservationToField;
        
        private System.Nullable<decimal> ReservationTotalFareField;
        
        private System.Nullable<int> ReservationTotalSeatField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationBusNumber {
            get {
                return this.ReservationBusNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationBusNumberField, value) != true)) {
                    this.ReservationBusNumberField = value;
                    this.RaisePropertyChanged("ReservationBusNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationDate {
            get {
                return this.ReservationDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationDateField, value) != true)) {
                    this.ReservationDateField = value;
                    this.RaisePropertyChanged("ReservationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationFrom {
            get {
                return this.ReservationFromField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationFromField, value) != true)) {
                    this.ReservationFromField = value;
                    this.RaisePropertyChanged("ReservationFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationIC {
            get {
                return this.ReservationICField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationICField, value) != true)) {
                    this.ReservationICField = value;
                    this.RaisePropertyChanged("ReservationIC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationID {
            get {
                return this.ReservationIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationIDField, value) != true)) {
                    this.ReservationIDField = value;
                    this.RaisePropertyChanged("ReservationID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationName {
            get {
                return this.ReservationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationNameField, value) != true)) {
                    this.ReservationNameField = value;
                    this.RaisePropertyChanged("ReservationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationPhoneNo {
            get {
                return this.ReservationPhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationPhoneNoField, value) != true)) {
                    this.ReservationPhoneNoField = value;
                    this.RaisePropertyChanged("ReservationPhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationSeatNumber {
            get {
                return this.ReservationSeatNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationSeatNumberField, value) != true)) {
                    this.ReservationSeatNumberField = value;
                    this.RaisePropertyChanged("ReservationSeatNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationTime {
            get {
                return this.ReservationTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationTimeField, value) != true)) {
                    this.ReservationTimeField = value;
                    this.RaisePropertyChanged("ReservationTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReservationTo {
            get {
                return this.ReservationToField;
            }
            set {
                if ((object.ReferenceEquals(this.ReservationToField, value) != true)) {
                    this.ReservationToField = value;
                    this.RaisePropertyChanged("ReservationTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ReservationTotalFare {
            get {
                return this.ReservationTotalFareField;
            }
            set {
                if ((this.ReservationTotalFareField.Equals(value) != true)) {
                    this.ReservationTotalFareField = value;
                    this.RaisePropertyChanged("ReservationTotalFare");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReservationTotalSeat {
            get {
                return this.ReservationTotalSeatField;
            }
            set {
                if ((this.ReservationTotalSeatField.Equals(value) != true)) {
                    this.ReservationTotalSeatField = value;
                    this.RaisePropertyChanged("ReservationTotalSeat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReference2.Service1")]
    public interface Service1 {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:Service1/Insert", ReplyAction="urn:Service1/InsertResponse")]
        System.IAsyncResult BeginInsert(Assignment1.ServiceReference2.Payment p, System.AsyncCallback callback, object asyncState);
        
        void EndInsert(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:Service1/LoadAll", ReplyAction="urn:Service1/LoadAllResponse")]
        System.IAsyncResult BeginLoadAll(string Id, System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Assignment1.ServiceReference2.Reservation> EndLoadAll(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1Channel : Assignment1.ServiceReference2.Service1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoadAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoadAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Assignment1.ServiceReference2.Reservation> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Assignment1.ServiceReference2.Reservation>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Assignment1.ServiceReference2.Service1>, Assignment1.ServiceReference2.Service1 {
        
        private BeginOperationDelegate onBeginInsertDelegate;
        
        private EndOperationDelegate onEndInsertDelegate;
        
        private System.Threading.SendOrPostCallback onInsertCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoadAllDelegate;
        
        private EndOperationDelegate onEndLoadAllDelegate;
        
        private System.Threading.SendOrPostCallback onLoadAllCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> InsertCompleted;
        
        public event System.EventHandler<LoadAllCompletedEventArgs> LoadAllCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Assignment1.ServiceReference2.Service1.BeginInsert(Assignment1.ServiceReference2.Payment p, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsert(p, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Assignment1.ServiceReference2.Service1.EndInsert(System.IAsyncResult result) {
            base.Channel.EndInsert(result);
        }
        
        private System.IAsyncResult OnBeginInsert(object[] inValues, System.AsyncCallback callback, object asyncState) {
            Assignment1.ServiceReference2.Payment p = ((Assignment1.ServiceReference2.Payment)(inValues[0]));
            return ((Assignment1.ServiceReference2.Service1)(this)).BeginInsert(p, callback, asyncState);
        }
        
        private object[] OnEndInsert(System.IAsyncResult result) {
            ((Assignment1.ServiceReference2.Service1)(this)).EndInsert(result);
            return null;
        }
        
        private void OnInsertCompleted(object state) {
            if ((this.InsertCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertAsync(Assignment1.ServiceReference2.Payment p) {
            this.InsertAsync(p, null);
        }
        
        public void InsertAsync(Assignment1.ServiceReference2.Payment p, object userState) {
            if ((this.onBeginInsertDelegate == null)) {
                this.onBeginInsertDelegate = new BeginOperationDelegate(this.OnBeginInsert);
            }
            if ((this.onEndInsertDelegate == null)) {
                this.onEndInsertDelegate = new EndOperationDelegate(this.OnEndInsert);
            }
            if ((this.onInsertCompletedDelegate == null)) {
                this.onInsertCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertCompleted);
            }
            base.InvokeAsync(this.onBeginInsertDelegate, new object[] {
                        p}, this.onEndInsertDelegate, this.onInsertCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Assignment1.ServiceReference2.Service1.BeginLoadAll(string Id, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLoadAll(Id, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Assignment1.ServiceReference2.Reservation> Assignment1.ServiceReference2.Service1.EndLoadAll(System.IAsyncResult result) {
            return base.Channel.EndLoadAll(result);
        }
        
        private System.IAsyncResult OnBeginLoadAll(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string Id = ((string)(inValues[0]));
            return ((Assignment1.ServiceReference2.Service1)(this)).BeginLoadAll(Id, callback, asyncState);
        }
        
        private object[] OnEndLoadAll(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Assignment1.ServiceReference2.Reservation> retVal = ((Assignment1.ServiceReference2.Service1)(this)).EndLoadAll(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoadAllCompleted(object state) {
            if ((this.LoadAllCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoadAllCompleted(this, new LoadAllCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoadAllAsync(string Id) {
            this.LoadAllAsync(Id, null);
        }
        
        public void LoadAllAsync(string Id, object userState) {
            if ((this.onBeginLoadAllDelegate == null)) {
                this.onBeginLoadAllDelegate = new BeginOperationDelegate(this.OnBeginLoadAll);
            }
            if ((this.onEndLoadAllDelegate == null)) {
                this.onEndLoadAllDelegate = new EndOperationDelegate(this.OnEndLoadAll);
            }
            if ((this.onLoadAllCompletedDelegate == null)) {
                this.onLoadAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoadAllCompleted);
            }
            base.InvokeAsync(this.onBeginLoadAllDelegate, new object[] {
                        Id}, this.onEndLoadAllDelegate, this.onLoadAllCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Assignment1.ServiceReference2.Service1 CreateChannel() {
            return new Service1ClientChannel(this);
        }
        
        private class Service1ClientChannel : ChannelBase<Assignment1.ServiceReference2.Service1>, Assignment1.ServiceReference2.Service1 {
            
            public Service1ClientChannel(System.ServiceModel.ClientBase<Assignment1.ServiceReference2.Service1> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginInsert(Assignment1.ServiceReference2.Payment p, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = p;
                System.IAsyncResult _result = base.BeginInvoke("Insert", _args, callback, asyncState);
                return _result;
            }
            
            public void EndInsert(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("Insert", _args, result);
            }
            
            public System.IAsyncResult BeginLoadAll(string Id, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Id;
                System.IAsyncResult _result = base.BeginInvoke("LoadAll", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Assignment1.ServiceReference2.Reservation> EndLoadAll(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Assignment1.ServiceReference2.Reservation> _result = ((System.Collections.ObjectModel.ObservableCollection<Assignment1.ServiceReference2.Reservation>)(base.EndInvoke("LoadAll", _args, result)));
                return _result;
            }
        }
    }
}
